package agent

import (
	"log/slog"
	"testing"
)

func TestCaptureAndRestoreBaseNetwork(t *testing.T) {
	bn := CaptureBaseNetwork()
	if bn == nil {
		t.Fatal("CaptureBaseNetwork returned nil")
	}

	// Restore should not panic or error even with nil logger
	bn.Restore(nil)
	bn.Restore(slog.Default())

	// Nil BaseNetwork should be safe
	var nilBN *BaseNetwork
	nilBN.Restore(nil)
}

func TestGetDefaultGateway(t *testing.T) {
	// Should return without crashing on any OS
	gw, iface := getDefaultGateway()
	_ = gw
	_ = iface
}

func TestPushedResolvers(t *testing.T) {
	// What a client installs is whatever the gateway named; what was there
	// before is the container's own resolver, which is reachable without the
	// tunnel and so proves nothing about it.
	tests := []struct {
		name    string
		base    string
		current string
		want    []string
	}{
		{
			name:    "openconnect replaced the resolver",
			base:    "nameserver 127.0.0.11\noptions ndots:0\n",
			current: "# Generated by vpnc-script\nnameserver 10.118.48.10\nnameserver 10.122.97.10\n",
			want:    []string{"10.118.48.10", "10.122.97.10"},
		},
		{
			name:    "the VPN added one and kept the container's",
			base:    "nameserver 127.0.0.11\n",
			current: "nameserver 10.76.144.3\nnameserver 127.0.0.11\n",
			want:    []string{"10.76.144.3"},
		},
		{
			name:    "nothing was installed",
			base:    "nameserver 127.0.0.11\n",
			current: "nameserver 127.0.0.11\n",
			want:    nil,
		},
		{
			name:    "a commented resolver is not one",
			base:    "nameserver 127.0.0.11\n",
			current: "nameserver 127.0.0.11\n# nameserver 10.0.0.1\n",
			want:    nil,
		},
	}
	for _, tt := range tests {
		t.Run(tt.name, func(t *testing.T) {
			got := pushedResolvers([]byte(tt.base), []byte(tt.current))
			if len(got) != len(tt.want) {
				t.Fatalf("pushed resolvers = %v, want %v", got, tt.want)
			}
			for i := range got {
				if got[i] != tt.want[i] {
					t.Errorf("resolver %d = %q, want %q", i, got[i], tt.want[i])
				}
			}
		})
	}
}
